export const ADD_CITY = 'ADD_CITY';
export const GET_ALL_CITIES = 'GET_ALL_CITIES';
export const GET_ALL_CITIES_SUCCEEDED = 'GET_ALL_CITIES_SUCCEEDED';
export const SET_SUBSCRIBED_CITIES_FROM_LOCAL_STORAGE = 'SET_SUBSCRIBED_CITIES_FROM_LOCAL_STORAGE';
export const SET_SUBSCRIBED_CITIES_FROM_LOCAL_STORAGE_SUCCEDED = 'SET_SUBSCRIBED_CITIES_FROM_LOCAL_STORAGE_SUCCEDED';

export const REFRESH_WEATHER = 'REFRESH_WEATHER';
export const REFRESH_WEATHER_SUCCEEDED = 'REFRESH_WEATHER_SUCCEEDED';

export const DELETE_CITY = 'DELETE_CITY';

export const GET_SUBSCRIBED_CITIES = 'GET_SUBSCRIBED_CITIES';
export const GET_SUBSCRIBED_CITIES_SUCCEEDED = 'GET_SUBSCRIBED_CITIES_SUCCEEDED';

export const ENABLE_LOADING = 'ENABLE_LOADING';
export const DISABLE_LOADING = 'DISABLE_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';