export const ADD_CITY = 'ADD_CITY';
export const GET_ALL_CITIES = 'GET_ALL_CITIES';
export const GET_ALL_CITIES_SUCCEEDED = 'GET_ALL_CITIES_SUCCEEDED';

export const REFRESH_WEATHER = 'REFRESH_WEATHER';
export const REFRESH_WEATHER_SUCCEEDED = 'REFRESH_WEATHER_SUCCEEDED';

export const DELETE_CITY = 'DELETE_CITY';

export const GET_SUBSCRIBED_CITIES = 'GET_SUBSCRIBED_CITIES';
export const GET_SUBSCRIBED_CITIES_SUCCEEDED = 'GET_SUBSCRIBED_CITIES_SUCCEEDED';